# Generated by Django 3.2.5 on 2021-11-10 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oyeda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoe',
            name='brand_slug',
            field=models.CharField(choices=[('nike', 'nike'), ('adidas', 'adidas'), ('puma', 'puma'), ('new-balance', 'new-balance'), ('vans', 'vans'), ('converse', 'converse')], default='nike', max_length=20),
        ),
    ]
