# Generated by Django 3.2.5 on 2021-09-30 20:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('oyeda', '0002_ordereditems_orderlist'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderedItems',
            new_name='OrderedItem',
        ),
        migrations.AddField(
            model_name='orderlist',
            name='items',
            field=models.ManyToManyField(to='oyeda.OrderedItem'),
        ),
    ]
