# Generated by Django 3.2.8 on 2021-11-29 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oyeda', '0002_shoe_brand_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriberEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='brand',
            name='btn_type',
            field=models.CharField(choices=[('primary', 'primary'), ('light', 'light'), ('danger', 'danger'), ('warning', 'warning'), ('light', 'light'), ('success', 'success'), ('info', 'info'), ('dark', 'dark')], max_length=20),
        ),
    ]
