# Generated by Django 3.2.8 on 2021-11-29 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oyeda', '0003_auto_20211129_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriberemail',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
