# Generated by Django 3.2.5 on 2021-10-01 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oyeda', '0003_auto_20210930_2054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordereditem',
            name='user',
        ),
    ]
