# Generated by Django 3.2.5 on 2021-10-01 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oyeda', '0004_remove_ordereditem_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlist',
            name='ordered',
            field=models.BooleanField(default=False),
        ),
    ]
