# Generated by Django 3.2.5 on 2021-10-27 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oyeda', '0008_auto_20211027_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlist',
            name='billing_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='oyeda.billingaddress'),
        ),
        migrations.AlterField(
            model_name='orderlist',
            name='shipping_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='oyeda.shippingaddress'),
        ),
    ]
