# Generated by Django 3.2.5 on 2021-11-01 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oyeda', '0010_auto_20211029_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlist',
            name='payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='oyeda.payment'),
        ),
    ]
