# Generated by Django 3.2.5 on 2021-11-05 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oyeda', '0011_orderlist_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoe',
            name='new_arrival',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='brand',
            field=models.CharField(choices=[('Nike', 'Nike'), ('Adidas', 'Adidas'), ('Puma', 'Puma'), ('New Balance', 'New Balance'), ('Vans', 'Vans'), ('Converse', 'Converse')], max_length=20),
        ),
    ]
