# Generated by Django 3.2.5 on 2021-11-05 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oyeda', '0012_auto_20211105_2125'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('btn_type', models.CharField(choices=[('primary', 'primary'), ('light', 'light'), ('danger', 'danger'), ('warning', 'warning'), ('light', 'light'), ('success', 'success')], max_length=20)),
                ('name', models.CharField(choices=[('Nike', 'Nike'), ('Adidas', 'Adidas'), ('Puma', 'Puma'), ('New Balance', 'New Balance'), ('Vans', 'Vans'), ('Converse', 'Converse')], max_length=20)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.AlterField(
            model_name='shoe',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oyeda.brand'),
        ),
    ]
